// TRIALS
export const LOAD_CURRENT_TRIAL_SUCCESS = 'LOAD_CURRENT_TRIAL_SUCCESS'
export const LOAD_CURRENT_TRIAL_FAIL = 'LOAD_CURRENT_TRIAL_SUCCESS'
export const UPDATE_TRIALS_SUCCESS = 'UPDATE_TRIALS_SUCCESS'
export const UPDATE_TRIALS_FAIL = 'UPDATE_TRIALS_FAIL'

// CURRENT
export const UPDATE_CURRENT_SUCCESS = 'UPDATE_CURRENT_SUCCESS' 
export const UPDATE_CURRENT_FAIL = 'UPDATE_CURRENT_FAIL' 
export const UPDATE_TRACKING_SUCCESS = 'UPDATE_TRACKING_SUCCESS' 
export const UPDATE_TRACKING_FAIL = 'UPDATE_TRACKING_FAIL' 
export const UPDATE_SCREEN = 'UPDATE_SCREEN'
export const UPDATE_SCREEN_FAIL = 'UPDATE_SCREEN_FAIL'

// CALIBRATION
export const UPDATE_CALIBRATION_SUCCESS = 'UPDATE_CALIBRATION_SUCCESS' 
export const UPDATE_CALIBRATION_FAIL = 'UPDATE_CALIBRATION_FAIL' 

// FORM
export const UPDATE_BULSHIT = 'UPDATE_BULSHIT' 
export const UPDATE_FORM = 'UPDATE_FORM' 
export const UPDATE_TRIAL_FORM = 'UPDATE_TRIAL_FORM' 
export const UPDATE_FORM_FAIL = 'UPDATE_FORM_FAIL' 
export const UPDATE_RISK = 'UPDATE_RISK' 
export const UPDATE_SCALE = 'UPDATE_SCALE' 

// EXPORT
export const LOAD_EXPORT_SUCCESS = 'LOAD_EXPORT_SUCCESS'
export const LOAD_EXPORT_FAIL = 'LOAD_EXPORT_FAIL'
export const UPDATE_EXPORT_SUCCESS = 'UPDATE_EXPORT_SUCCESS'
export const UPDATE_EXPORT_FAIL = 'UPDATE_EXPORT_FAIL'

// RESET 
export const RESET_STORE = 'RESET_STORE'

// FULLSCREEN 
export const FULLSCREEN_RECORD = 'FULLSCREEN_RECORD'