export const fr = {
    button: 'Continuer',
    next: 'Suivant',
    button1: 'Commencer',
    button2: 'Valider',
    button3: "Commencer l'experimentation",
    button4: "Essai suivant",
    button5: 'Pause',
    button6: 'Révéler',
    home_title: 'Bienvenue',
    home_corps1: `Nous souhaitons mieux comprendre les processus de <b>la prise de décisions financières et d'investissement</b>.
        Pour cette étude, des <b>vrais</b> documents financiers, concernant différents fonds d'investissement, vous seront présentées.
        Ensuite, vous devrez répondre à plusieurs questions sur ces sujets. Vos réponses resteront totalement confidentielles. La durée de l'étude est d'environ <b>30 minutes</b>.`,
    home_corps2: `Votre participation à l'étude est volontaire. En continuant, vous confirmez avoir a minima 18 ans. Vous pouvez choisir de mettre fin à votre participation à tout moment.
    Vous pouvez contacter les chercheurs responsables de l'étude à l'adresse e-mail suivante :<i><u>milos.borozan@univ-rouen.fr</u></i>.`,
    home_corps3: `<i>Aucune donnée individuelle ne sera traitée, seuls des résultats combinés avec d’autres participants à ce test seront analysés. </i>`,
    contact: `contact : <u>milos.borozan@univ-rouen.fr</u>`,
    form_title: 'Informations nécessaires',
    form_corps1: 'Veuillez compléter le formulaire ci dessous. Les informations resterons anonymes et confidentielles.',
    form_age: 'Âge',
    form_genre: ['Genre', 'Homme', 'Femme', 'Autre'],
    form_prof: 'Quelle est votre profession ?',
    form_pay: 'Quel jour du mois êtes-vous généralement rémunéré?',
    form_main: ['Main dominante', 'Droite', 'Gauche'],
    form_souris: ['Main sur la souris', 'Droite', 'Gauche'],
    form_accept: `En poursuivant, je donne mon consentement à l'utilisation des données me concernant sous forme anonyme et agrégée, à des fins de recherche scientifique. <br /> J'accepte volontairement de participer à l'étude et je comprends que je peux me retirer de l'étude à tout moment, sans donner d'explications.`,
    calib_corps1: `Comme mentionné précédemment, au cours de cette expérience, nous utiliserons les technologies de suivi oculaire et de suivi de la souris.
    Avant de commencer, pour vous familiariser avec la manière dont l'étude est menée, nous ferons <b>quelques tentatives de test</b>.
    Cette phase permettra également l'étalonnage des instruments.`,
    calib_label: ['Gauche', 'Droite'],
    calib_consigne1: ['Après avoir cliqué sur le bouton de départ "+", vous devez cliquer le plus rapidement possible sur le bouton en haut à', "de l'écran."],
    calib_consigne2: `Les options seront affichées une fois la ligne rouge dépassée (<i><b>Attention</b> ! la ligne n'est pas visible pendant la tâche</i>).`,
    risk_question: `<b>Dans quelle mesure êtes-vous prêt à prendre des risques, en général ?</b> <i>Avant de répondre, prenez un moment pour réfléchir à votre expérience et aux décisions que vous avez prises dans différents domaines (éducation, relations, santé, achats, investissements, etc.) et différents moments de votre vie.</i>`,
    risk_lab: ['Pas du tout envie de prendre des risques', 'Pleinement prêt à prendre des risques'],
    bomb_revard: 'Récompense potentielle',
    bomb_revard2: 'Boxes restantes',
    bomb_miss: `Ooooops... <b>Vous avez fait exploser la bombe</b>.. !`,
    bomb_ok: `Félicitations, <b>la bombe n'a pas explosé</b> ! Vous avez gagné.`,
    bomb_task1: `Commençons par un jeu ! Sur la page suivante, vous verrez un champ composé de 64 boîtes. Votre tâche consiste à <b>collecter autant de boîtes que possible</b>. Vous gagnez <b>1 point</b> pour chaque boîte collectée.`,
    bomb_task2: `Attention, cependant, dans l'une de ces boîtes est <b>cachée une bombe</b> qui détruit l'ensemble des boîtes. Vous ne savez pas où se trouve cette bombe. La position de la bombe a été déterminée au hasard au préalable. La bombe peut <b>se trouver dans n'importe quelle boîte avec la même probabilité</b>.`,
    bomb_task3: `Si vous collectez la boîte où se trouve la bombe, <b>la bombe explosera et vous détruira l'ensemble de vos gains</b>. Si vous vous arrêtez avant de collecter la bombe, vous gagnerez les points accumulés jusque-là.`,
    bomb_task4: `<b>Chaque seconde, une boîte est collectée</b> et vous choisissez quand <b>arrêter</b> le processus de collecte en appuyant sur « <b>pause</b> » à tout moment. Vous pouvez voir le montant gagné actuel.`,
    bomb_task5: `Lorsque vous souhaitez arrêter, vous pouvez cliquer sur le bouton « <b>révéler</b> » pour découvrir le contenu des boites.`,
    bomb_task6: `Le jeu consiste en <b>6 essais</b> indépendants.`,
    consigne_un_corps1: `Ça c’était amusant, non ?`,
    consigne_un_corps2: `Passons maintenant aux décisions financières. Avant de commencer, il est essentiel que vous compreniez bien de quoi il s'agit, veuillez donc <b>suivre attentivement</b> toutes les instructions.`,
    consigne_un_corps3: `Les décisions d'investissement sont généralement basées sur les données de différentes entreprises ou fonds d'investissement qu'un utilisateur prend en considération. Ces données sont présentées de <b>manière standardisée</b> dans les documents financiers (<i>image 1</i>).`,
    consigne_un_corps4: `Chaque document financier <b>a la même structure</b>. Nous allons maintenant vous montrer une brève vidéo qui l'explique plus en détail.`,
    consigne_trois_corps1: `Maintenant, nous vous demanderons <b>d'examiner attentivement certains documents financiers</b> similaires à celui que vous venez de voir. (<i>image 2</i>).`,
    consigne_trois_corps2: `Le temps disponible pour consulter chaque document financier <b>sera limité</b> et il est donc crucial que vous sachiez <b>où rechercher</b> les informations les plus importantes pour vous.`,
    consigne_trois_corps3: `Ainsi, pour vous permettre de bien vous familiariser avec la structure et le contenu d'un document financier type, nous allons vous montrer à nouveau le document de la vidéo.`,
    consigne_cinq_corps1: `Maintenant, si vous avez <b>des questions</b> sur le document, son contenu, la terminologie et les objectifs des différentes informations, <b>n'hésitez pas à me les poser</b>.`,
    consigne_cinq_corps2: `Sinon, si tout est clair, vous pouvez continuer en cliquant sur le bouton ci-dessous.`,
    consigne_six_corps1: `Après chaque document, l'interface de choix vous sera présentée et vous devrez décider si vous souhaitez investir dans le fonds qui vient d'être présenté. (<i>image 3</i>).`,
    consigne_six_corps2: `Vous devez répondre aussi <b>rapidement</b> et <b>précisément</b> que possible.`,
    consigne_six_corps3: `Veuillez considérer chaque document <b>séparément</b>. Aussi,veuillez agir comme si vous investissiez <b>votre propre argent<b> car nous évaluerons vos performances en tant qu'investisseur.`,
    consigne_image1: `<i><u>Image 1</u></i> : Un document financier.`,
    consigne_image2: `<i><u>Image 2</u></i> : Interface de document financier.`,
    consigne_image3: `<i><u>Image 3</u></i> : Interface de choix.`,
    choice_lab: ['Non', 'Oui'],
    choice_q1: "D'après les informations affichées, investiriez-vous votre argent dans ce fonds d'investissement ?",
    choice_q2: "Vous devez répondre le plus rapidement et précisément possible.",
    question_un_q: "Veuillez indiquer votre niveau de confiance concernant cette décision sur l'échelle ci-dessous.",
    question_un_lab: ['Complétement incertain', 'Complétement sûr'],
    question_deux_q: `Vous souvenez-vous du <b>niveau de risque</b> indiqué du fonds d'investissement que vous venez de considérer ? Veuillez l'indiquer à l'aide de l'échelle ci-dessous.`,
    question_trois_q: "L'information présentée était-elle juste suffisante pour prendre votre décision d'investissement ?",
    question_trois_lab: ["Pas du tout suffisante / Vous auriez besoin d'informations supplémentaires pour prendre une décision", 'Complétement suffisante'],
    question_quatre_q: `Quel type d'informations a été <b>le plus important</b> pour votre décision ?`,
    question_quatre_lab: ['Peu important', 'Très important'],
    question_quatre_options: ['Frais', 'Profil de risque et de rendement', "Objectifs et politique d'investissement", 'Performances passées'],
    scale_un: "Dans quelle mesure vous êtes-vous fié à votre expérience personnelle pour prendre cette décision ?",
    scale_un_value: ["Pas du tout", "Complétement"],
    scale_deux: "Veuillez indiquer dans quelle mesure cette décision était pertinente pour vous sur l'échelle ci-dessous.",
    scale_deux_value: ["Pas du tout", "Complétement"],
    scale_trois: "Veuillez indiquer le niveau d'effort que la prise de cette décision vous a demandé sur l'échelle ci-dessous.",
    scale_trois_value: ["Très faible", "Très important"],
    scale_quatre: "Quelle est votre expérience avec ce type de décision ?",
    scale_quatre_value: ["Aucune", "Importante"],
    scale_cinq: "Supposons que vous disposiez de 100 € sur un compte d'épargne et que le taux d'intérêt était de 2 % par an. Après 5 ans, combien pensez-vous que vous auriez sur le compte si vous laissiez l'argent fructifier ?",
    scale_cinq_value: ["Plus de 102 €", "Exactement 102 €", "Moins de 102 €"],
    scale_six: "Imaginez que le taux d'intérêt sur votre compte d'épargne était de 1 % par an et que l'inflation était de 2 % par an. Après 1 an, combien seriez-vous en mesure d'acheter avec l'argent de ce compte ?",
    scale_six_value: ["Plus qu'aujourd'hui", "Exactement le même", "Moins qu'aujourd'hui"],
    scale_sept: "Si les taux d'intérêt augmentent, qu'arrivera-t-il généralement aux prix des obligations ?",
    scale_sept_value: ["Ils augmenteront", "Ils diminueront", "Ils resteront les mêmes", "Il n'y a pas de relation entre le prix des obligations et le taux d'intérêt"],
    scale_huit: "Un prêt hypothécaire de 15 ans nécessite généralement des versements mensuels plus élevés qu'un prêt hypothécaire de 30 ans, mais le total des intérêts payés sur la durée du prêt sera inférieur.",
    scale_neuf: "L'achat d'actions d'une seule entreprise offre généralement un rendement plus sûr qu'un fonds commun de placement.",
    scale_neuf_huit_value: ["Vrai", "Faux"],
    scale_dix: "Une batte et une balle coûtent 1,10 $ au total. La batte coûte 1,00 $ de plus que la balle. Combien coûte la balle ?",
    scale_dix_value: ["1 cent", "5 cent", "10 cent"],
    scale_onze: "S'il faut 5 minutes à 5 machines pour fabriquer 5 articles, combien de temps faudrait-il à 100 machines pour fabriquer 100 articles ?",
    scale_onze_value: ["1 minute", "5 minutes", "100 minutes"],
    scale_douze: "Dans un lac, il y a une parcelle de nénuphars. Chaque jour, la taille de la parcelle double. S'il faut 48 jours pour que la parcelle couvre tout le lac, combien de temps faudrait-il pour que la parcelle couvre la moitié du lac ?",
    scale_douze_value: ["12 jours", "24 jours", "47 jours"],
    scale_corps: "C'est presque terminé ! Vous devez répondre à quelques questions.",
    scale_corps1: "Encore une dernière étape.",
    bulshit_label: ["Pas du tout significatif / Ne vaut pas du tout la peine d'être considéré", "Très peu significatif / Vaut peu la peine d'être considéré", "Légèrement significatif / Vaut légèrement la peine d'être considéré", "Plutôt significatif / Vaut plutôt la peine d'être considéré", "Significatif / Vaut la peine d'être considéré", "Très significatif / Vaut largement la peine d'être considéré"],
    bulshit1: "Un imbécile et son argent sont bientôt séparés", 
    bulshit2: "Un budget nous indique ce que nous ne pouvons pas nous offrir, mais il ne nous empêche pas de l'acheter.",
    bulshit3: "La finance ne consiste pas seulement à faire de l'argent. Il s'agit de réaliser nos objectifs profonds et de protéger le fruit de notre travail.",
    bulshit4: "Chaque que fois que vous empruntez de l'argent, vous vous volez dans votre futur.",
    bulshit5: "L'inflation est une taxation sans législation.",
    bulshit6: "La richesse n'est pas à celui qui la possède, mais à celui qui en jouit.",
    bulshit7: "Un prêt bon marché est au-delà de tout nouveau destin.", 
    bulshit8: "Votre argent transforme des actions universelles.", 
    bulshit9: "L'argent allège les coûts de ceux qui empruntent.", 
    bulshit10: "La richesse et la persévérance fournissent de l'argent au pauvre.",
    bulshit11: "Les bons investisseurs répartissent les grandes actions au-delà de la taille.",
    bulshit12: "La liberté et l'espace transforment le sens abstrait de l'argent.",
    bulshit_corps: `Veuillez évaluer <b>le niveau de signification des phrases suivantes</b> concernant les finances à l'aide d'une échelle de six points donnée.`,
    distress_header: 'Choisissez les réponses les plus appropriées  <b><u>à votre situation</u></b>.',
    distress1: `Selon vous, quel est votre niveau de <b><u>stress financier aujourd'hui</u></b> ?`,
    distress_label1: ['Stress accablant', 'Stress élevé', 'Stress faible', 'Pas de stress du tout'],
    distress2: `Sur l'échelle ci-dessous, indiquez dans quelle mesure vous êtes satisfait de votre <b><u>situation financière actuelle</u></b>.`,
    distress_label2: ['Insatisfaction totale', '', '', 'Entière satisfaction'],
    distress3: `Que pensez-vous de votre <b><u>situation financière actuelle</u></b> ?`,
    distress_label3: ['Dépassé', 'Parfois inquiet', "Ne pas m'inquiéter", "Je me sens à l'aise"],
    distress4: `À quelle fréquence vous inquiétez-vous de pouvoir faire face à vos dépenses mensuelles normales ?`,
    distress_label4: ["M'inquiéter tout le temps", "M'inquiéter parfois", "M'inquiéter rarement", "Ne jamais m'inquiéter"],
    distress5: `Dans quelle mesure êtes-vous sûr de pouvoir trouver l'argent nécessaire pour faire face à <b><u>une urgence financière</u></b> qui coûterait environ <b><u>1000€</b></u> ?`,
    distress_label5: ['Aucune confiance', 'Peu de confiance', 'Une certaine confiance', 'Une grande confiance'],
    distress6: `À quelle fréquence cela vous arrive-t-il de ne pas sortir manger, de ne pas aller au cinéma ou de ne pas faire autre chose parce que <b><u>vous n'en avez pas les moyens</u></b> ?`,
    distress_label6: ['Tout le temps', 'Parfois', 'Rarement', 'Jamais'],
    distress7: `À quelle fréquence arrivez-vous à vous <b><u>débrouiller financièrement et à épargner</u></b> ?`,
    distress_label7: ['Tout le temps', 'Parfois', 'Rarement', 'Jamais'],
    distress8: `Dans quelle mesure vous sentez-vous stressé par <b><u>vos finances personnelles en général</u></b> ?`,
    distress_label8: ['Stress accablant', 'Stress élevé', 'Stress faible', 'Pas de stress du tout'],
    temporal_header: "À l'aide de l'échelle ci-dessous, veuillez indiquer la fréquence à laquelle vous pensez à la période indiquée par l'item.",
    temporal1: "Je pense à des choses de mon passé.",
    temporal2: "Je vis ma vie dans le moment présent.",
    temporal3: "Je pense à ce que mon avenir me réserve.",
    temporal4: "Je me concentre sur ce qui se passe actuellement dans ma vie.",
    temporal5: "Je me concentre sur mon avenir.",
    temporal6: "Je rejoue des souvenirs du passé dans mon esprit.",
    temporal7: "J'imagine ce que demain m'apportera.",
    temporal8: "Mon esprit est dans le moment présent.",
    temporal9: "Je réfléchis à ce qu'il m'est arrivé au cours de ma vie.",
    temporal10: "Je pense à là où j'en suis aujourd'hui.",
    temporal11: "Je repense à mes premières années.",
    temporal12: "Je pense aux moments à venir.",
    temporal_label: ['Jamais', 'Parfois', 'Fréquemment', 'Constamment'],
    intro_test1: "Eeet c'est fini. Nous espérons que vous avez bien aimé être dans le rôle d'un investisseur, car vous l'avez fait de manière incroyable !",
    intro_test2: 'Maintenant, nous allons désactiver les dispositifs de suivi oculaire et de suivi de la souris et nous vous demanderons de bien vouloir répondre à questions avant de terminer.',
    intro_test3: 'Merci pour votre patience!',
    end: "Merci de votre participation."
}

export const it = {
    button: 'Continua',
    next: 'Avanti',
    button1: 'Inizia',
    button2: 'Accetta e continua',
    button3: "Inizia l'esperimento",
    button4: "Essai suivant",
    button5: 'Stop',
    button6: 'Reveal',
    home_title: 'Benvenutə',
    home_corps1: `Ciao! Grazie al tuo aiuto, vogliamo comprendere meglio i <b>processi decisionali finanziari</b>. In questo studio ti mostreremo dei <b>veri</b> documenti finanziari relativi a diversi fondi di investimento. In seguito, ti chiederemo di rispondere ad alcune domande. Le tue risposte rimarranno completamente confidenziali. Lo studio durerà circa <b>30 minuti</b>.`,
    home_corps2: `La tua partecipazione allo studio è volontaria. Continuando, confermi di avere almeno 18 anni e di voler prendere parte allo studio. Se lo desideri, puoi scegliere di terminare la tua partecipazione in qualsiasi momento.
    Se hai dubbi o domande, potrai  contattare il ricercatore responsabile dello studio al seguente indirizzo mail:
<i><u>milos.borozan@unich.it</u></i>.`,
    home_corps3: `<i>I dati non verranno analizzati singolarmente, ma solo in forma aggregata, facendo una media delle risposte di tutti i partecipanti.</i>`,
    contact: `contatto : <u>milos.borozan@univ-rouen.fr</u>`,
    form_title: 'Informazioni personali',
    form_corps1: 'Per favore inserisci i tuoi dati nei campi indicati sotto. Ti ricordiamo che tutte le informazioni fornite saranno trattate in forma anonima e confidenziale.', 
    form_age: 'Età',
    form_genre: ['Genere', 'Maschile', 'Femminile', 'Altro'],
    form_prof: 'Qual è la tua professione?',
    form_pay: 'Che giorno del mese al solito ricevi lo stipendio?',
    form_main: ['La mano dominante', 'Destra', 'Sinistra'],
    form_souris: ['La mano sul mouse', 'Destra', 'Sinistra'],
    form_accept: `Proseguendo, acconsento all'utilizzo dei miei dati in forma anonima e aggregata, per finalità di ricerca scientifica. <br />Accetto volontariamente di partecipare allo studio, sapendo che posso ritirarmi dallo studio in qualsiasi momento, senza fornire alcuna spiegazione.`,
    calib_corps1: `Come già accenato, lo studio prevede l'utilizzo di tecnologie di eye-tracking e mouse-tracking per la raccolta dei dati.
    Prima di iniziare, per farti familiarizzare con lo studio, faremo <b> alcuni tentativi di prova</b>.
    Questa fase consentirà inoltre di calibrare ancora gli strumenti.`,
    calib_label: ['Sinistra', 'Destra'],
    calib_consigne1: ['Dopo aver fatto clic sul pulsante di avvio "+" collocato in basso, cerca di fare clic sul pulsante collocato nella "parte superiore', 'dello schermo", il più velocemente e accuratamente possibile'],
    calib_consigne2: `Le alternative di scelta verranno visualizzate una volta superata la linea rossa (<i><b>Attenzione</b> ! la linea non sarà visibile più avanti durante il compito</i>).`,
    risk_question: `<b>Reputi di essere una persona che, in generale, è completamente preparata a correre dei rischi oppure che i rischi preferisce evitarli?</b>
<i>(Prima di rispondere, ti chiediamo di prenderti un momento per riflettere sulla tua esperienza e sulle decisioni che hai preso in diversi contesti (istruzione, relazioni, salute, acquisti, investimenti, ecc.) e in momenti diversi della tua vita.)</i>`,
    risk_lab: ['Preferisco evitare i rischi', 'Completamente preparatə a correre dei rischi'],
    bomb_revard: 'Potenziale guadagno',
    bomb_revard2: 'Numero di scatole rimaste',
    bomb_miss: `Ooooops... <b>Hai beccato la scatola con la bomba dentro.</b>`,
    bomb_ok: `Bravissimə! <b>La bomba non è esplosa</b> e hai vinto!`,
    bomb_task1: `Iniziamo con un gioco! Nella pagina successiva, vedrai un campo composto da 64 scatole. Il tuo compito è <b>raccogliere quante più scatole possibili</b>. Per ogni scatola raccolta guadagni <b>10 punti</b>.`,
    bomb_task2: `Tuttavia, in una di queste scatole è <b>nascosta una bomba</b>. Se raccogli la scatola con la bomba dentro, <b>la bomba esploderà e guadagnerai zero punti</b>. Se ti fermerai prima di raccogliere la bomba, guadagnerai i punti accumulati fino a quel momento.`,
    bomb_task3: `La posizione esatta della bomba è sconosciuta - può trovarsi <b>in qualsiasi scatola con uguale probabilità</b>. Inoltre, la posizione è stata determinata in anticipo e in modo casuale.`,
    bomb_task4: `<b>Ogni secondo</b> viene raccolta una scatola e sei tu a scegliere quando vuoi fermarti premendo il pulsante <b>“Stop”</b> in qualsiasi momento. Nella parte sinistra dello schermo puoi vedere l’importo che avrai potenzialmente guadagnato in ogni momento.`,
    bomb_task5: `Dopo aver finito, fai clic sul pulsante <b>“Reveal”</b>  per scoprire se hai vinto oppure hai raccolto la bomba.`,
    bomb_task6: `Inizieremo con <b>una sessione di prova</b>, che ha il solo scopo di mostrarti come funziona il gioco. Dopodiché, inizierà il gioco vero e proprio.`,
    consigne_un_corps1: `Questa è stata divertente, no?`,
    consigne_un_corps2: `Adesso passiamo alle decisioni di investimento. Prima di iniziare, è importante che tu capisca bene di cosa si tratti, perciò ti chiediamo di <b>seguire tutte le istruzioni attentamente</b>.`,
    consigne_un_corps3: `Le decisioni di investire oppure non investire solitamente si basano sui dati finanziari delle società oppure dei fondi di investimento che prendiamo in considerazione. Questo tipo di dati è presentato <b>in modo standardizzato</b> nei documenti finanziari. (<i>imagine 1</i>)`,
    consigne_un_corps4: `Ogni documento finanziario ha <b>la stessa struttura</b>. Adesso ti presenteremo un breve video che la spiega in dettaglio.`,
    consigne_trois_corps1: `Adesso, ti chiederemo di <b>esaminare attentamente</b> alcuni documenti finanziari <b>simili a quello che hai appena visto</b>. (<i>imagine 2</i>)`,
    consigne_trois_corps2: `Il tempo a disposizione per consultare ogni documento finanziario sarà <b>limitato</b, per cui è essenziale che tu sappia bene <b>dove cercare</b le informazioni che ritieni importanti.`,
    consigne_trois_corps3: `Perciò, ti presenteremo ancora una volta il documento mostrato nel video per permetterti di esaminarlo in dettaglio.`,
    consigne_cinq_corps1: `Se hai qualunque dubbio, riguardo per esempio il documento, i suoi contenuti, la terminologia usata oppure il significato di alcune informazioni, per favore non esitare di chiedermelo.`,
    consigne_cinq_corps2: `Altrimenti, se è tutto chiaro, puoi procedere cliccando sul bottone sotto.`,
    consigne_six_corps1: `In seguito ad ogni documento, ti verrà presentata l'interfaccia di scelta e dovrai decidere se investire o meno nel fondo appena presentato. (<i>imagine 3</i>)`,
    consigne_six_corps2: `Per favore rispondi il più <b>rapidamente</b> e <b>accuratamente</b> possibile.`,
    consigne_six_corps3: `Ti chiediamo di considerare ogni documento <b>separatamente</b>. Inoltre, ti chiediamo di comportarti come se stessi investendo <b>il tuo denaro</b>, perché dopo valuteremo le tue performances come investitore.`,
    consigne_image1: `<i><u>Imagine 1</u></i> : Un documento finanziario.`,
    consigne_image2: `<i><u>Imagine 2</u></i> : Interfaccia del documento finanziario.`,
    consigne_image3: `<i><u>Imagine 3</u></i> : Interfaccia di scelta.`,
    choice_lab: ['No', 'Sì'],
    choice_q1: "Sulla base delle informazioni che hai appena visto; investiresti i tuoi soldi in questo fondo?",
    choice_q2: "Per favore rispondi il più rapidamente e accuratamente possibile.",
    question_un_q: "Valuta il tuo livello di fiducia in questa decisione utilizzando la scala sottostante.",
    question_un_lab: ['Del tutto incertə', 'Del tutto certə'],
    question_deux_q: `Indica <b>lil livello di rischio</b> stimato del fondo di investimento che hai appena visto utilizzando la scala sottostante.`,
    question_trois_q: "Le informazioni presentate sono state sufficienti per prendere una decisione?",
    question_trois_lab: ["Del tutto insufficienti / Avrei bisogno di informazioni aggiuntive per prendere una decisione", 'Del tutto sufficienti'],
    question_quatre_q: `Quale tipo di informazione è stata più importante per la tua decisione? Indica l’importanza relativa di ognuna di esse utilizzando la scala sottostante.`,
    question_quatre_lab: ['Non così importante', 'Molto importante'],
    question_quatre_options: ['Spese', 'Obiettivi e politica d’investimento', "Profilo di rischio e di rendimento", 'Rendimenti ottenuti nel passato'],
    scale_un: "In che misura ti sei fidatə delle tue esperienze e preferenze per prendere la decisione?",
    scale_un_value: ["Per niente", "Tanto"],
    scale_deux: "Quanto è rilevante una tale decisione per te personalmente??",
    scale_deux_value: ["Per niente rilevante", "Molto rilevante"],
    scale_trois: "Quanto impegno ha richiesto il prendere una buona decisione?",
    scale_trois_value: ["Nessuno", "Tanto"],
    scale_quatre: "Quanta esperienza hai con questo tipo di decisioni?",
    scale_quatre_value: ["Nessuna", "Molta"],
    scale_cinq: "Immagina di avere 100 euro depositati in un conto corrente che prevede il tasso di interesse annuo del 2%. Tra 5 anni, se non farai né prelievi né versamenti, senza considerare le spese di gestione e la tassazione, a quanto pensi ammonterà il tuo saldo sul conto corrente?",
    scale_cinq_value: ["Più di 110 €", "Esattamente 110 €", "Meno di 110 €"],
    scale_six: "Ipotizziamo che il tuo tasso d’interesse sul tuo conto corrente, che non applica spese di gestione, sia pari all’1% annuo e che l’inflazione si attesti al 2% annuo. Dopo un anno, con il denaro sul tuo conto corrente sarai in grado di acquistare:",
    scale_six_value: ["Più di oggi", "Esattamente come oggi", "Meno di oggi"],
    scale_sept: "Se i tassi di interesse aumentano, cosa accadrà in genere ai prezzi delle obbligazioni?",
    scale_sept_value: ["Aumenteranno", "Scenderanno", "Rimarranno uguali", "Non c’è una relazione tra i prezzi delle obbligazioni e i tassi di interesse"],
    scale_huit: "Un mutuo di 15 anni richiede in genere pagamenti mensili più elevati rispetto a un mutuo di 30 anni, ma l’ammontare totale degli interessi pagato durante il prestito sarà inferiore",
    scale_neuf: "L’acquisto di azioni di una singola società di solito è un investimento meno rischioso rispetto all’acquisto di quote di un fondo comune azionario.",
    scale_neuf_huit_value: ["Vero", "Falso"],
    scale_dix: "Una mazza da baseball e una palla costano 1,10 euro in totale. La mazza costa 1 euro più della palla. Quanto costa la palla? ",
    scale_dix_value: ["1 centesimo", "5 centesimi", "10 centesimi"],
    scale_onze: "Se 5 macchine costruiscono 5 gadget in 5 minuti, quanto tempo impiegheranno 100 macchine per costruire 100 gadget?",
    scale_onze_value: ["1 minuto", "5 minuti", "100 minuti"],
    scale_douze: "In un lago ci sono delle ninfee che ogni giorno duplicano la loro superficie. Se impiegano 48 giorni per ricoprire l’intero lago, quanto impiegheranno per coprirne la metà?",
    scale_douze_value: ["12 giorni", "24 giorni", "47 giorni"],
    scale_corps: "Speriamo che l'esperienza ti stia piacendo! Ti chiederemo di rispondere ancora a qualche domanda prima di concludere.",
    scale_corps1: "Solo un altro passo.",
    bulshit_label: ["Per niente significativo/per niente degno di considerazione", "Poco significativo/poco degno di considerazione", "Leggermente significativo/leggermente degno di considerazione", "Piuttosto significativo/piuttosto degno di considerazione", "Significativo/degno di considerazione", "Molto significativo/molto degno di considerazione"],
    bulshit1: "Uno sciocco e il suo denaro sono presto separati.", 
    bulshit2: "Un budget ci dice quando una cosa non ce la possiamo permettere, ma non ci impedisce di acquistarla lo stesso.",
    bulshit3: "La finanza non riguarda solo il fare soldi. Si tratta di raggiungere i nostri obiettivi profondi e proteggere i frutti del nostro lavoro.",
    bulshit4: "Ogni volta che prendi del denaro in prestito, stai derubando il tuo futuro te stesso.",
    bulshit5: "L'inflazione è tassazione senza legislazione.",
    bulshit6: "La ricchezza non è di chi ce l'ha, ma di chi se la gode.",
    bulshit7: "Un prestito a buon mercato è al di là di ogni nuovo destino.", 
    bulshit8: "Il tuo denaro trasforma le azioni universali.", 
    bulshit9: "Il denaro alleggerisce i costi di chi lo prende in prestito.", 
    bulshit10: "Ricchezza e perseveranza forniscono il denaro per i poveri.",
    bulshit11: "I buoni investitori diffondono delle grandi azioni oltre le dimensioni.",
    bulshit12: "Libertà e spazio trasformano il significato astratto del denaro.",
    bulshit_corps: `Indica <b>il livello di significatività delle seguenti frasi</b> riguardanti la finanza utilizzando la scala sottostante a sei punti.`,
    distress_header: 'Seleziona la risposta che meglio rappresenta <b><u>la tua situazione attuale</u></b>.',
    distress1: `Quale ritieni sia il <b><u>livello</u></b> del <b><u>tuo stress finanziario oggi</u></b>?`,
    distress_label1: ['Stress opprimente', 'Stress elevato', 'Stress basso', 'Nessun stress'],
    distress2: `Sulla scala sottostante, seleziona quanto sei <b><u>soddisfattə</u></b> della tua <b><u>attuale situazione finanziaria</u></b>`,
    distress_label2: ['Completa insoddisfazione', '', '', 'Completa soddisfazione'],
    distress3: `Come ti senti riguardo alla <b><u>tua situazione finanziaria attuale</u></b>?`,
    distress_label3: ['Sopraffattə', 'A volte preoccupatə', 'Non preoccupatə', 'A proprio agio'],
    distress4: `Quanto spesso <b><u>le normali spese di vitto</u></b> rappresentano una fonte di preoccupazione?`,
    distress_label4: ['Sempre', 'A volte', 'Raramente', 'Mai'],
    distress5: `Se dovessi trovarti in una situazione di <b><u>emergenza finanziaria</u></b>, quanto si sentiresti sicurə di essere in grado di trovare circa <b><u>1000€</u></b> per affrontarla?`,
    distress_label5: ['Per niente fiduciosə', 'Poco fiduciosə', 'Fiduciosə', 'Altamente fiduciosə'],
    distress6: `Quanto spesso ti è capitato di voler uscire a mangiare fuori, andare al cinema o fare qualcos’altro e <b><u>non farlo perché non te lo puoi permettere</u></b>?`,
    distress_label6: ['Sempre', 'A volte', 'Raramente', 'Mai'],
    distress7: `Quanto spesso ti capita di dover stare attentə per <b><u>arrivare a fine mese</u></b>?`,
    distress_label7: ['Sempre', 'A volte', 'Raramente', 'Mai'],
    distress8: `Quanto ti senti stressatə per le <b><u>tue finanze personali in generale</u></b>?`,
    distress_label8: ['Stress opprimente', 'Stress elevato', 'Stress basso', 'Nessun stress'],
    temporal_header: "Utilizzando la scala sottostante, indica la frequenza con cui pensi all’intervallo di tempo indicato dall’item.",
    temporal1: "Penso a cose vissute nel mio passato.",
    temporal2: "Vivo la mia vita nel presente.",
    temporal3: "Penso a ciò che ha in serbo il mio futuro.",
    temporal4: "Mi concentro su ciò che accade attualmente nella mia vita.",
    temporal5: "Rivivo nella mia mente i ricordi del passato.",
    temporal6: "Immagino cosa mi porterà il domani.",
    temporal7: "La mia mente è indirizzata sul qui e ora.",
    temporal8: "Rifletto su ciò che è accaduto nella mia vita.",
    temporal9: "Ripenso ai giorni passati.",
    temporal10: "Penso ai momenti che verranno.",
    temporal11: "NA",
    temporal12: "NA",
    temporal_label: ['Mai', 'A volte ', 'Frequentemente ', 'Costantemente'],
    intro_test1: "Abbiamo finito con i documenti! Speriamo ti sia piaciuta l'esperienza, perché hai fatto un ottimo lavoro.",
    intro_test2: "Adesso spegneremo i dispositivi di eye-tracking e di mouse-tracking e ti chiederemo gentilmente di rispondere (<b>ancora</b>) a qualche domanda prima di concludere.",
    intro_test3: "Grazie per la pazienza!",
    end: "Grazie per la tua partecipazione."
}

export const en = {
    button: 'Continue',
    next: 'Next',
    button1: 'Start',
    button2: 'Accept and continue',
    button3: "Start the experiment",
    button4: "Next round",
    button5: 'Stop',
    button6: 'Reveal',
    home_title: 'Welcome',
    home_corps1: `With your help, we would like to better understand the <b>financial decision-making processes</b>.
        To do so, in this study we will show you <b>real</b> financial information concerning different investment funds. Afterwards, we will ask you to respond to a few questions. Your responses will remain completely confidential. The study will take around <b>30 minutes</b>.`,
    home_corps2: `Your participation in the study is voluntary. By continuing, you confirm that you are at least 18 years old. You can choose to end your participation at any time.
     If you should have any questions or comments, you can contact the researcher responsible for the study at the following email address: <i><u>milos.borozan@univ-rouen.fr</u></i>.`,
    home_corps3: `<i>The data will not be analysed individually, but only in aggregated form, with the data of all participants.</i>`,
    contact: `contact : <u>milos.borozan@univ-rouen.fr</u>`,
    form_title: 'Necessary information',
    form_corps1: 'Please enter your details in the fields below. All information will remain anonymous and confidential.', 
    form_age: 'Age',
    form_genre: ['Gender', 'Male', 'Female', 'Other'],
    form_prof: 'What is your profession?',
    form_pay: 'Which day of the month do you usually receive your salary?',
    form_main: ['Dominant hand', 'Right', 'Left'],
    form_souris: ['Hand on the mouse', 'Right', 'Left'],
    form_accept: `By continuing, I give my consent to the use of my data in anonymous and aggregated form, for the purposes of scientific research. <br />I voluntarily agree to participate in the study and I understand that I can withdraw from the study at any time, without giving any explanation.`,
    calib_corps1: `As already mentioned, during this experiment we will use eye-tracking and mouse-tracking technologies.
    Before we begin, to make you familiarize with how the study is conducted, we will do <b> a few test trials</b>.
    This phase will also help better calibrate the instruments.`,
    calib_label: ['Left', 'Right'],
    calib_consigne1: ['After you click on the start button  "+" located at the bottom of the screen, please click as fast as possible on the button on "top', 'of your screen"'],
    calib_consigne2: `The choice options will be displayed once you cross the red line (<i><b>Attention</b> ! the line will not be visible later during the task</i>).`,
    risk_question: `<b>How do you see yourself - are you generally a person who is fully prepared to take risks or do you try to avoid taking risks?</b> <i>(Before you answer, please take a moment to reflect on your experience and the decisions you have made in different areas (education, relationships, health, shopping, investing, etc.) and different times in your life.)</i>`,
    risk_lab: ['Unwilling to take risks', 'Fully prepared to take risks'],
    bomb_revard: 'Potential reward',
    bomb_revard2: 'Remaining boxes',
    bomb_miss: `Ooooops... <b>You picked up the box containing the bomb.</b>. !`,
    bomb_ok: `Congratulations, <b>the bomb didn't explode</b>! You have won.`, 
    bomb_task1: `Let’s start with a game ! On the next page, you will see a field composed of 64 boxes. Your task is to <b>collect as many boxes as possible</b> because you earn <b>1 points</b> for each and every collected box.`,
    bomb_task2: `However, one of these boxes hides <b>a bomb</b> that destroys everything. If you collect the box where the bomb is located, <b>the bomb will explode, and you earn zero</b>. If you stop before collecting the bomb, you gain the points accumulated that far. `,
    bomb_task3: `You do not know where this bomb lies. The position of the bomb has been randomly determined beforehand and it can be <b>in any place with equal probability</b>.`,
    bomb_task4: `<b>Every second</b> a box is collected, and <b>you choose when to stop the collecting process by hitting “Stop” at any time</b>. Your earnings are updated and in any moment you can see the amount earned up to that point.`,
    bomb_task5: `After you have finished, you click on <b>“Reveal”</b> button to discover if you have won or you have collected the bomb.`,
    bomb_task6: `We will start with <b>a practice round</b>, which is only meant to show how the experiment works. After that, the real game will start.`,
    consigne_un_corps1: `That was fun, right?`,
    consigne_un_corps2: `Now we will move on to the financial decisions. Before starting, it is essential that you fully understand what is going on, so please follow all instructions <b>carefully</b>.`, 
    consigne_un_corps2: `Investment decisions are usually based on data on different companies or investment funds that a user takes into consideration. This type of data is presented <b>in a standardized way</b> in the financial documents (<i>image 1</i>).`,
    consigne_un_corps4: `Each financial document has <b>the same structure</b>. Now we will show you a brief video that explains it in more detail.`,
    consigne_trois_corps1: `Now, for the main task, we will ask you to carefully review certain financial documents <b>similar to the one you have just seen</b>. (<i>Image 2</i>)`,
    consigne_trois_corps2: `The time available to consult each financial document will be <b>limited</b> so it's crucial that you know <b>where to search</b> for the information most important for you.`,
    consigne_trois_corps3: `To allow you to familiarize well with a typical financial document, its structure and content, we will show you once again the document from the video.`,
    consigne_cinq_corps1: `Now, if you have <b>any questions</b>, for instance about the document, its content or the terminology used, please don't hesitate to ask me.`,
    consigne_cinq_corps2: `Otherwise, if everything is clear, you can proceed by clicking the button below.`,
    consigne_six_corps1: `After each document, you'll be presented with the choice interface, and you will have to <b>decide whether you want to invest</b> in the Fund just presented. (<i>Image 3</i>).`,
    consigne_six_corps2: `You must respond as <b>quickly</b> and <b>accurately</b> as possible.`,
    consigne_six_corps3: `Please consider each document <b>separately</b>. Also, please do as if you were investing <b>your own money</b>, because we will evaluate your perfomances as an investor.`,
    consigne_image1: `<i><u>Image 1</u></i> : Financial document`,
    consigne_image2: `<i><u>Image 2</u></i> : Financial document interface`,
    consigne_image3: `<i><u>Image 3</u></i> : Choice interface`,
    choice_lab: ['No', 'Yes'],
    choice_q1: "Based on the information that you just saw, would you invest your money in this fund?",
    choice_q2: "You must respond as quickly and accurately as possible.",
    question_un_q: "Please rate your level of confidence in this decision on the scale below.",
    question_un_lab: ['Completely unsure', 'Completely sure'],
    question_deux_q: `Do you remember the <b>level of risk</b> indicated for the investment fund you have just considered? Please indicate using the scale below.`,
    question_trois_q: "Was the information presented sufficient for you to make your investment decision?",
    question_trois_lab: ["Not at all sufficient / You would need additional information to make the decision", 'Completely sufficient'],
    question_quatre_q: `What type of information was the most important to your decision? Please indicate their relative importance using the scale below.?`,
    question_quatre_lab: ['Not so important', 'Very important'],
    question_quatre_options: ['Charges', 'Objectives and investment policy', "Risk and reward profile", 'Past performance'],
    scale_un: "How much have you relied on your own experiences and preferences to make the decision?",
    scale_un_value: ["Not at all", "A lot"],
    scale_deux: "How relevant is such a decision for you personally?",
    scale_deux_value: ["Not at all relevant", "Very relevant"],
    scale_trois: "How much effort have you put in to make a good decision?",
    scale_trois_value: ["No effort at all", "A lot of effort"],
    scale_quatre: "How much experience do you have with this kind of decision?",
    scale_quatre_value: ["No experience at all", "A lot of experience"],
    scale_cinq: "Suppose you had $100 in a savings account and the interest rate was 2% per year. After 5 years, how much do you think you would have in the account if you left the money to grow?",
    scale_cinq_value: ["More than 110 €", "Exactly 110 €", "Less than 110 €"],
    scale_six: "Imagine that the interest rate on your savings account was 1% per year and inflation was 2% per year. After 1 year, how much would you be able to buy with the money in this account?",
    scale_six_value: ["More than today", "Exactly the same", "Less than today"],
    scale_sept: "If interest rates rise, what will typically happen to bond prices?",
    scale_sept_value: ["They will rise", "They will fall", "They will stay the same", "There is no relationship between bond prices and the interest rate"],
    scale_huit: "A 15-year mortgage typically requires higher monthly payments than a 30-year mortgage, but the total interest paid over the life of the loan will be less.",
    scale_neuf: "Buying a single company’s stock usually provides a safer return than a stock mutual fund.",
    scale_neuf_huit_value: ["True", "False"],
    scale_dix: "A bat and a ball cost 1,10€ in total. The bat costs 1€ more than the ball. How much does the ball cost?",
    scale_dix_value: ["1 cent", "5 cents", "10 cents"],
    scale_onze: "If it takes 5 machines 5 minutes to make 5 widgets, how long would it take 100 machines to make 100 widgets?",
    scale_onze_value: ["1 minute", "5 minutes", "100 minutes"],
    scale_douze: "In a lake, there is a patch of lily pads. Every day, the patch doubles in size. If it takes 48 days for the patch to cover the entire lake, how long would it take for the patch to cover half of the lake?",
    scale_douze_value: ["12 days", "24 days", "47 days"],
    scale_corps: "We hope that you are enjoying the experience. Before we finish, we would like to kindly ask you to answer a few more questions.",
    scale_corps1: "Just one more step.",
    bulshit_label: ["Not at all meaningful/worth considering", "Hardly meaningful/worth considering", "Slightly meaningful/worth considering", "Rather meaningful/worth considering", "Meaningful/worth considering", "Very meaningful/worth considering"],
    bulshit1: "A fool and his money are soon parted.", 
    bulshit2: "A budget tells us what we can’t afford, but it doesn’t keep us from buying it.",
    bulshit3: "Finance is not merely about making money. It’s about achieving our deep goals and protecting the fruits of our labor.",
    bulshit4: "Every time you borrow money, you are robbing your future self.",
    bulshit5: "Inflation is taxation without legislation.",
    bulshit6: "Wealth is not his that has it, but his that enjoys it.",
    bulshit7: "A cheap loan is beyond all new destiny.", 
    bulshit8: "Your money transforms universal actions.", 
    bulshit9: "Money eases the costs of those who borrow.", 
    bulshit10: "Wealth and perseverance provide money for the poor.",
    bulshit11: "Good investors spread large shares beyond size.",
    bulshit12: "Freedom and space transform the abstract meaning of money.",
    bulshit_corps: `Please rate <b>the level of meaningfulness of the following sentences</b> regarding finances using a given six-point scale.`,
    distress_header: 'Check the responses that are most appropriate for your situation.',
    distress1: `What do you feel is the <b><u>level</u></b> of your <b><u>financial stress today</u></b>?`,
    distress_label1: ['Overwhelming stress', 'High stress', 'Low stress', 'No Stress at all'],
    distress2: `On the scale below, mark how <b><u>satisfied</u></b> you are with your <b><u>present financial situation</u></b>`,
    distress_label2: ['Complete dissatisfaction', '', '', 'Complete satisfaction'],
    distress3: `How do you feel about your <b><u>current financial situation</u></b>?`,
    distress_label3: ['Feel Overwhelmed', 'Sometimes Feel Worried', 'Not Worried', 'Feel Comfortable'],
    distress4: `How often do you worry about being <b><u>able to meet</u></b>? normal monthly living expenses?`,
    distress_label4: ['Worry all the time', 'Sometimes Worry', 'Rarely worry', 'Never worry'],
    distress5: `How confident are you that you could find the money to pay for a <b><u>financial emergency</u></b> that costs about <b><u>1,000€</u></b> ?`,
    distress_label5: ['No Confidence', 'Little Confidence', 'Some Confidence', 'High Confidence'],
    distress6: `How often does this happen to you? You want to go out to eat, go to a movie or do something else and <b><u>don’t go because you can’t afford to</u></b>?`,
    distress_label6: ['All the time', 'Sometimes', 'Rarely', 'Never'],
    distress7: `How frequently do you find yourself just getting by financially and living <b><u>paycheck to paycheck?</u></b>`,
    distress_label7: ['All the time', 'Sometimes', 'Rarely', 'Never'],
    distress8: `How <b><u>stressed</u></b> do you feel about your personal finances <b><u>in general</u></b>?`,
    distress_label8: ['Overwhelming stress', 'High stress', 'Low stress', 'No Stress at all'],
    temporal_header: "Using the scale below, please indicate the frequency with which you think about the time frame indicated by the item.",
    temporal1: "I think about things from my past.",
    temporal2: "I live my life in the present.",
    temporal3: "I think about what my future has in store.",
    temporal4: "I focus on what is currently happening in my life.",
    temporal5: "I focus on my future.",
    temporal6: "I replay memories of the past in my mind.",
    temporal7: "I imagine what tomorrow will bring for me.",
    temporal8: "My mind is on the here and now.",
    temporal9: "I reflect on what has happened in my life.",
    temporal10: "I think about where I am today.",
    temporal11: "I think back to my earlier days.",
    temporal12: "I think about times to come.",
    temporal_label: ['Never', 'Sometimes', 'Frequently', 'Constantly'],
    intro_test1: "Aaand that's a wrap for the documents. We hope that you liked being an investor, because you did an amazing job!",
    intro_test2: 'Now we will turn off the eye-tracking and the mouse-tracking and we will kindly ask you (<i>again</i>) to answer a few more questions before concluding.',
    intro_test3: 'Thank you for your patience!',
    end: "Thank you for your participation."
}