export const fr = {
    button: 'Continuer',
    next: 'Suivant',
    button1: 'Commencer',
    button2: 'Valider',
    button3: "Commencer l'experimentation",
    home_title: 'Bienvenue',
    home_corps1: `Nous souhaitons mieux comprendre les processus de <b>la prise de décisions financières et d'investissement</b>.
        Pour cette étude, des informations concernant différents fonds d'investissement vous seront présentées.
        Ensuite, vous devrez répondre à plusieurs questions sur ces sujets. Vos réponses resteront totalement confidentielles.  La durée de l'étude est d'environ <b>20 minutes</b>.`,
    home_corps2: `Votre participation à l'étude est volontaire. En continuant, vous confirmez avoir a minima 18 ans. Vous pouvez choisir de mettre fin à votre participation à tout moment.
    Vous pouvez contacter les chercheurs responsables de l'étude à l'adresse e-mail suivante : <i><u>milos.borozan@univ-rouen.fr</u></i>.`,
    home_corps3: `<i>Aucune donnée individuelle ne sera traitée, seuls des résultats combinés avec d’autres participants à ce test seront analysés. </i>`,
    contact: `contact :  <u>milos.borozan@univ-rouen.fr</u>`,
    form_title: 'Informations nécessaires',
    form_corps1: 'Veuillez compléter le formulaire ci dessous. Les informations resterons anonymes et confidentielles.',
    form_age: 'Âge',
    form_genre: ['Genre', 'Homme', 'Femme', 'Autre'],
    form_prof: 'Quelle est votre profession ?',
    form_main: ['Main dominante', 'Droite', 'Gauche'],
    form_souris: ['Main sur la souris', 'Droite', 'Gauche'],
    form_accept: `En poursuivant, je donne mon consentement à l'utilisation des données me concernant sous forme anonyme et agrégée, à des fins de recherche scientifique. <br /> J'accepte volontairement de participer à l'étude et je comprends que je peux me retirer de l'étude à tout moment, sans donner d'explications.`,
    calib_corps1: `Au cours de cette expérience, nous utiliserons les technologies de suivi oculaire et de suivi de la souris.
    Avant de commencer, pour vous familiariser avec la manière dont l'étude est menée, nous ferons <b>quelques tentatives de test</b>.
    Cette phase permettera également l'étalonnage des instruments.`,
    calib_corps2: `Sur la page suivante, une <b>croix</b> apparaîtra. Vous devez la <b>fixer continuellement</b>.`,
    calib_label: ['Gauche', 'Droite'],
    calib_consigne1: ['Après avoir cliquer sur le boutton de départ "+", vous devez cliquer le plus rapidement possible sur le boutton en haut à', "de l'écran."],
    calib_consigne2: `Les options seront affichées une fois la ligne rouge dépassé (<i><b>Attention</b> ! la ligne n'est pas visible pendant la tâche</i>).`,
    risk_question: `<b>Dans quelle mesure êtes-vous prêt à prendre des risques, en général ?</b> <i>Avant de répondre, prenez un moment pour réfléchir à votre expérience et aux décisions que vous avez prises dans différents domaines (éducation, relations, santé, achats, investissement, etc.) et différents moments de votre vie.</i>`,
    risk_lab: ['Pas du tout envie de prendre des risques', 'Pleinement prêt à prendre des risques'],
    risk_corps1: `Vous allez participez à <b>un petit jeu rapide</b> avant de poursuivre vers l'expérimentation.
    Veuillez regarder dans la <b>fenêtre à droite/gauche et suivre les instructions du jeu</b>.    `,
    risk_corps2: ` Après avoir terminé, revenez à cette fenêtre et <b>saisissez manuellement votre performance</b> dans les champs ci-dessous.`,
    risk_form: ['Essai', 'Uniquement des nombres'],
    consigne_un_corps1: `L’objectif de cette section est de décrire le déroulement global de l'expérimentation. Veuillez lire <b>attentivement</b> l’ensemble des instructions.`,
    consigne_un_corps2: `Les décisions d'investissement sont généralement basées sur les données de différentes entreprises ou fonds d'investissement qu'un utilisateur prend en considération. Ces données sont présentées de manière standardisée dans les documents financiers (<i>image 1</i>).`,
    consigne_un_corps3: `Chaque document financier présente la même structure et comporte 4 sections : "<b>Frais</b> ", "<b>Objectifs et politique d'investissement</b>", "<b>Profil de risque et de rendement</b>" et "<b>Performances passées</b> ".`,
    consigne_deux_corps1: `Par conséquent, nous vous demanderons <b>d'examiner attentivement certains documents financiers</b>.
    Ensuite nous vous poserons quelques <b>questions</b> à ce sujet et une interface de choix vous sera présentée (<i>image 2</i>). Vous devrez répondre le plus <b>rapidement</b> et <b>précisément</b> possible.`,
    consigne_deux_corps2: ` Le temps disponible pour consulter chaque document financier sera <b>limité</b>.
    Veuillez considérer chaque document séparément.
    Nous vous rappelons qu’il <b>n'y a pas de bonnes ou de mauvaises réponses</b>, nous ne nous intéressons qu'à vos propres préférences.`,
    consigne_deux_corps3: `Avant de débuter, un exemple de document financier va vous être présenté, sans limite de temps. Cliquez simplement sur continuer pour débuter l'expérimentation.`,
    consigne_image1: `<i><u>Image 1</u></i> : interface relative aux informations sur un fonds d'investissement`,
    consigne_image2: `<i><u>Image 2</u></i> : interface de choix.`,
    choice_lab: ['Non', 'Oui'],
    choice_q1: "D'après les informations affichées, investiriez-vous votre argent dans ce fonds d'investissement ?",
    choice_q2: "Vous devez répondre le plus rapidement et précisément possible.",
    question_un_q: "Veuillez indiquer votre niveau de confiance concernant cette décision sur l'échelle ci-dessous.",
    question_un_lab: ['Complétement incertain', 'Complément sûr'],
    question_deux_q: `Vous souvenez-vous du <b>niveau de risque</b> indiqué du fonds d'investissement que vous venez de considérer ? Veuillez l'indiquer à l'aide de l'échelle ci-dessous.`,
    question_trois_q: "L'information présentée était-elle juste suffisante pour prendre votre décision d'investissement ?",
    question_trois_lab: ["Pas du tout suffisant / Vous auriez besoin d'informations supplémentaire pour prendre une décision", 'Complément suffisant'],
    question_quatre_q: `Quel type d'information a été <b>le plus important</b> pour votre décision ?`,
    question_quatre_lab: ['Peu important', 'Très important'],
    question_quatre_options: ['Frais', 'Profil de risque et de rendement', "Objectifs et politique d'investissement", 'Performances passées'],
    scale_un: "Dans quelle mesure vous êtes-vous fié à votre expérience personnelle pour prendre cette décision ?",
    scale_un_value: ["Pas du tout", "Complément"],
    scale_deux: "Veuillez indiquer dans quelle mesure cette décision était pertinente pour vous sur l'échelle ci-dessous.",
    scale_deux_value: ["Pas du tout", "Complément"],
    scale_trois: "Veuillez indiquer le niveau d'effort que la prise de cette décision vous a demandé sur l'échelle ci-dessous.",
    scale_trois_value: ["Très faible", "Très important"],
    scale_quatre: "Quelle est votre expérience avec ce type de décisions ?",
    scale_quatre_value: ["Aucune", "Importante"],
    scale_cinq: "Supposons que vous disposiez de 100 € sur un compte d'épargne et que le taux d'intérêt était de 2 % par an. Après 5 ans, combien pensez-vous que vous auriez sur le compte si vous laissiez l'argent fructifier ?",
    scale_cinq_value: ["Plus de 102 €", "Exactement 102 €", "Moins de 102 €", "Je ne sais pas", "Je préfère ne rien dire"],
    scale_six: "Imaginez que le taux d'intérêt sur votre compte d'épargne était de 1 % par an et que l'inflation était de 2 % par an. Après 1 an, combien seriez-vous en mesure d'acheter avec l'argent de ce compte ?",
    scale_six_value: ["Plus qu'aujourd'hui", "Exactement le même", "Moins qu'aujourd'hui", "Je ne sais pas", "Je préfère ne rien dire"],
    scale_sept: "Si les taux d'intérêt augmentent, qu'arrivera-t-il généralement aux prix des obligations ?",
    scale_sept_value: ["Ils augmenteront", "Ils diminueront", "Ils resteront les mêmes", "Il n'y a pas de relation entre le prix des obligations et le taux d'intérêt", "Je ne sais pas", "Je préfère ne rien dire"],
    scale_huit: "Un prêt hypothécaire de 15 ans nécessite généralement des versements mensuels plus élevés qu'un prêt hypothécaire de 30 ans, mais le total des intérêts payés sur la durée du prêt sera inférieur.",
    scale_neuf: "L'achat d'actions d'une seule entreprise offre généralement un rendement plus sûr qu'un fonds commun de placement.",
    scale_neuf_huit_value: ["Vrai", "Faux", "Je ne sais pas", "Je préfère ne rien dire"],
    scale_dix: "Une batte et une balle coûtent 1,10 $ au total. La batte coûte 1,00 $ de plus que la balle. Combien coûte la balle ?",
    scale_dix_value: ["1 cent", "5 cent", "10 cent"],
    scale_onze: "S'il faut 5 minutes à 5 machines pour fabriquer 5 articles, combien de temps faudrait-il à 100 machines pour fabriquer 100 articles ?",
    scale_onze_value: ["1 minute", "5 minutes", "10 minutes"],
    scale_douze: "Dans un lac, il y a une parcelle de nénuphars. Chaque jour, la taille de la parcelle double. S'il faut 48 jours pour que la parcelle couvre tout le lac, combien de temps faudrait-il pour que la parcelle couvre la moitié du lac ?",
    scale_douze_value: ["12 jours", "24 jours", "47 jours"],
    scale_corps: "C'est presque terminé ! Vous devez répondre à quelques questions.",
    scale_corps1: "Encore une dernière étape.",
    bulshit_label: ["Pas du tout significatif / Ne vaut pas du tout la peine d'être considéré", "Très peu significatif / Vaut peu la peine d'être considéré", "Légèrement significatif / Vaut légèrement la peine d'être considéré", "Plutôt significatif / Vaut plutôt la peine d'être considéré", "Significatif / Vaut la peine d'être considéré", "Très significatif / Vaut largement la peine d'être considéré"],
    bulshit1: "Un imbécile et son argent sont bientôt séparés", 
    bulshit2: "Un budget nous indique ce que nous ne pouvons pas nous offrir, mais il ne nous empêche pas de l'acheter.",
    bulshit3: "La finance ne consiste pas seulement à faire de l'argent. Il s'agit de réaliser nos objectifs profonds et de protéger le fruit de notre travail.",
    bulshit4: "Chaque que fois que vous empruntez de l'argent, vous vous volez dans votre futur.",
    bulshit5: "L'inflation est une taxation sans législation.",
    bulshit6: "La richesse n'est pas à celui qui la possède, mais à celui qui en jouit.",
    bulshit7: "Un prêt bon marché est au-delà de tout nouveau destin.", 
    bulshit8: "Votre argent transforme des actions universelles.", 
    bulshit9: "L'argent allège les coûts de ceux qui empruntent.", 
    bulshit10: "La richesse et la persévérance fournissent de l'argent au pauvre.",
    bulshit11: "Les bons investisseurs répartissent les grandes actions au-delà de la taille.",
    bulshit12: "La liberté et l'espace transforment le sens abstrait de l'argent.",
    bulshit_corps: `Veuillez évaluer <b>le niveau de signification des phrases suivantes</b> concernant les finances à l'aide d'une échelle de six points donnée.`,
    end: "Merci de votre participation."
}


export const it = {
    button: 'Continua',
    next: 'Avanti',
    button1: 'Inizia',
    button2: 'Accetta e continua',
    button3: "Inizia l'esperimento",
    home_title: 'Benvenutə',
    home_corps1: `Ciao! Grazie al tuo aiuto, Vorremmo comprendere meglio i <b>processi decisionali finanziari</b>. In questo studio ti mostreremo informazioni finanziarie relative a diversi fondi di investimento. In seguito, ti chiederemo di rispondere ad alcune domande. Le tue risposte rimarranno completamente confidenziali. Lo studio durerà circa <b>20 minuti</b>.`,
    home_corps2: `La tua partecipazione allo studio è volontaria. Continuando, confermi di avere almeno 18 anni e di voler prendere parte allo studio. Se lo desideri, potrai scegliere di terminare la tua partecipazione in qualsiasi momento.
    Se hai dubbi o domande, puoi  contattare il ricercatore responsabile dello studio al seguente indirizzo mail:
<i><u>milos.borozan@univ-rouen.fr</u></i>.`,
    home_corps3: `<i>I dati non verranno analizzati singolarmente, ma solo in forma aggregata, facendo una media di tutte le risposte date dai partecipanti.</i>`,
    contact: `contatto :  <u>milos.borozan@univ-rouen.fr</u>`,
    form_title: 'Informazioni personali',
    form_corps1: 'Per favore inserisci i tuoi dati nei campi indicati sotto. Ti ricordiamo che tutte le informazioni fornite saranno trattate in forma anonima e confidenziale.', 
    form_age: 'Età',
    form_genre: ['Genere', 'Maschile', 'Femminile', 'Altro'],
    form_prof: 'Qual è la tua professione?',
    form_main: ['La mano dominante', 'Destra', 'Sinistra'],
    form_souris: ['La mano sul mouse', 'Destra', 'Sinistra'],
    form_accept: `Proseguendo, acconsento all'utilizzo dei miei dati in forma anonima e aggregata, per finalità di ricerca scientifica. <br />Accetto volontariamente di partecipare allo studio, sapendo che posso ritirarmi dallo studio in qualsiasi momento, senza fornire alcuna spiegazione.`,
    calib_corps1: `Lo studio prevede l'utilizzo di tecnologie di eye-tracking e mouse-tracking per la raccolta dei dati.
    Prima di iniziare, per farti familiarizzare con lo studio, faremo <b> alcuni tentativi di prova</b>.
     Questa fase consentirà inoltre di calibrare gli strumenti.`,
    calib_corps2: `Nella pagina successiva apparirà una <b>croce</b>. <b>Ti preghiamo di fissarla per tutto il tempo</b>.`,
    calib_label: ['Sinistra', 'Destra'],
    calib_consigne1: ['Dopo aver fatto clic sul pulsante di avvio "+", cerca di fare clic sul pulsante collocato nella "parte superiore', 'dello schermo", il più velocemente e accuratamente possibile'],
    calib_consigne2: `Le alternative di scelta verranno visualizzate una volta superata la linea rossa (<i><b>Attenzione</b> ! la linea non sarà visibile più avanti durante il compito</i>).`,
    risk_question: `<b>Reputi di essere una persona che, in generale, è completamente preparata a correre dei rischi oppure che i rischi preferisce evitarli?</b>
<i>(Prima di rispondere, ti chiediamo di prenderti un momento per riflettere sulla tua esperienza e sulle decisioni che hai preso in diversi contesti (istruzione, relazioni, salute, acquisti, investimenti, ecc.) e in momenti diversi della tua vita.)</i>`,
    risk_lab: ['Preferisco evitare i rischi', 'Completamente preparatə a correre dei rischi'],
    risk_corps1: `Parteciperai a <b>un piccolo gioco veloce</b> prima di continuare l'esperimento.
     Vai alla <b>finestra sulla tua destra/sinistra e segui le istruzioni di gioco</b>.`,
    risk_corps2: ` Quando avrai finito, torna a questa finestra e <b>inserisci manualmente i risultati del gioco</b> nei campi sottostanti.`, 
    risk_form: ['Tentativo', 'Inserire solo numeri'],
    consigne_un_corps1: `Lo scopo di questa sezione è descrivere bene la struttura dell'esperimento. Ti chiediamo di leggere tutte le istruzioni <b>attentamente</b>.`, 
    consigne_un_corps2: `Le decisioni di investire oppure non investire solitamente si basano sui dati finanziari delle società oppure dei fondi di investimento che prendiamo in considerazione. Questo tipo di dati è presentato in modo standardizzato nei documenti finanziari (<i>image 1</i>).`,
    consigne_un_corps3: `Ogni documento finanziario ha la stessa struttura e si compone di 4 sezioni: 
    "<b>Spese</b> ", "<b>Obiettivi e politica d’investimento</b>", "<b>Profilo di rischio e di rendimento</b>" e "<b>Rendimenti ottenuti nel passato</b> ".`,
    consigne_deux_corps1: `Pertanto, ti chiederemo di <b>esaminare attentamente alcuni documenti finanziari</b>. In seguito, ti faremo alcune <b>domande</b> a riguardo e ti verrà presentata l'interfaccia di scelta. (<i>image 2</i>). Ti chiediamo di rispondere il più <b>rapidamente</b> e <b>accuratamente</b> possibile.`,
    consigne_deux_corps2: ` Il tempo a disposizione per consultare ogni documento finanziario sarà <b>limitato</b>. Ti chiediamo di considerare ogni documento separatamente. Inoltre, ti ricordiamo che non ci sono <b>risposte giuste o sbagliate</b>, poiché a noi interessano solo le tue sincere preferenze.`,
    consigne_deux_corps3: `Prima di iniziare, per farti familiarizzare con i documenti, ti presentiamo un documento finanziario, che potrai esaminare senza limiti di tempo. Per iniziare, fai clic su continua.`,
    consigne_image1: `<i><u>Image 1</u></i> : Interfaccia di documento finanziario`,
    consigne_image2: `<i><u>Image 2</u></i> : Interfaccia di scelta`,
    choice_lab: ['No', 'Sì'],
    choice_q1: "Sulla base delle informazioni che hai appena visto; investiresti i tuoi soldi in questo fondo?",
    choice_q2: "Per favore rispondi il più rapidamente e accuratamente possibile.",
    question_un_q: "Valuta il tuo livello di fiducia in questa decisione utilizzando la scala sottostante.",
    question_un_lab: ['Del tutto incerto', 'Del tutto certo'],
    question_deux_q: `Indica <b>lil livello di rischio</b> indicato del fondo di investimento che hai appena visto utilizzando la scala sottostante.`,
    question_trois_q: "Le informazioni presentate sono state sufficienti per prendere una decisione?",
    question_trois_lab: ["Del tutto insufficienti / Avrei bisogno di informazioni aggiuntive per prendere una decisione", 'Del tutto sufficienti'],
    question_quatre_q: `Quale tipo di informazione è stata più importante per la tua decisione? Indica l’importanza relativa di ognuna di esse utilizzando la scala sottostante.`,
    question_quatre_lab: ['Non così importante', 'Molto importante'],
    question_quatre_options: ['Spese', 'Obiettivi e politica d’investimento', "Profilo di rischio e di rendimento", 'Rendimenti ottenuti nel passato'],
    scale_un: "In che misura ti sei fidatə delle tue esperienze e preferenze per prendere la decisione?",
    scale_un_value: ["Per niente", "Tanto"],
    scale_deux: "Quanto è rilevante una tale decisione per te personalmente??",
    scale_deux_value: ["Per niente rilevante", "Molto rilevante"],
    scale_trois: "Quanto impegno ha richiesto il prendere una buona decisione?",
    scale_trois_value: ["Nessuno", "Tanto"],
    scale_quatre: "Quanta esperienza hai con questo tipo di decisioni?",
    scale_quatre_value: ["Nessuna", "Molta"],
    scale_cinq: "Immagina di avere 100 euro depositati in un conto corrente che prevede il tasso di interesse annuo del 2%. Tra 5 anni, se non farai né prelievi né versamenti, senza considerare le spese di gestione e la tassazione, a quanto pensi ammonterà il tuo saldo sul conto corrente?",
    scale_cinq_value: ["Più di 110 €", "Esattamente 110 €", "Meno di 110 €", "Non so", "Preferisco non rispondere"],
    scale_six: "Ipotizziamo che il tuo tasso d’interesse sul tuo conto corrente, che non applica spese di gestione, sia pari all’1% annuo e che l’inflazione si attesti al 2% annuo. Dopo un anno, con il denaro sul tuo conto corrente sarai in grado di acquistare:",
    scale_six_value: ["Più di oggi", "Esattamente come oggi", "Meno di oggi", "Non so", "Preferisco non rispondere"],
    scale_sept: "Se i tassi di interesse aumentano, cosa accadrà in genere ai prezzi delle obbligazioni?",
    scale_sept_value: ["Aumenteranno", "Scenderanno", "Rimarranno uguali", "Non c’è una relazione tra i prezzi delle obbligazioni e i tassi di interesse", "Non so", "Preferisco non rispondere"],
    scale_huit: "Un mutuo di 15 anni richiede in genere pagamenti mensili più elevati rispetto a un mutuo di 30 anni, ma l’ammontare totale degli interessi pagato durante il prestito sarà inferiore",
    scale_neuf: "L’acquisto di azioni di una singola società di solito è un investimento meno rischioso rispetto all’acquisto di quote di un fondo comune azionario.",
    scale_neuf_huit_value: ["Vero", "Falso", "Non so", "Preferisco non rispondere"],
    scale_dix: "Una mazza da baseball e una palla costano 1,10 euro in totale. La mazza costa 1 euro più della palla. Quanto costa la palla? ",
    scale_dix_value: ["1 centesimo", "5 centesimi", "10 centesimi"],
    scale_onze: "Se 5 macchine costruiscono 5 gadget in 5 minuti, quanto tempo impiegheranno 100 macchine per costruire 100 gadget?",
    scale_onze_value: ["1 minuto", "5 minuti", "10 minuti"],
    scale_douze: "In un lago ci sono delle ninfee che ogni giorno duplicano la loro superficie. Se impiegano 48 giorni per ricoprire l’intero lago, quanto impiegheranno per coprirne la metà?",
    scale_douze_value: ["12 giorni", "24 giorni", "47 giorni"],
    scale_corps: "È quasi finita! Dovete rispondere ad alcune domande.",
    scale_corps1: "Solo un altro passo.",
    bulshit_label: ["Per niente significativo/per niente degno di considerazione", "Poco significativo/poco degno di considerazione", "Leggermente significativo/leggermente degno di considerazione", "Piuttosto significativo/piuttosto degno di considerazione", "Significativo/degno di considerazione", "Molto significativo/molto degno di considerazione"],
    bulshit1: "Uno sciocco e il suo denaro sono presto separati.", 
    bulshit2: "Un budget ci dice quando una cosa non ce la possiamo permettere, ma non ci impedisce di acquistarla lo stesso.",
    bulshit3: "La finanza non riguarda solo il fare soldi. Si tratta di raggiungere i nostri obiettivi profondi e proteggere i frutti del nostro lavoro.",
    bulshit4: "Ogni volta che prendi del denaro in prestito, stai derubando il tuo futuro te stesso.",
    bulshit5: "L'inflazione è tassazione senza legislazione.",
    bulshit6: "La ricchezza non è di chi ce l'ha, ma di chi se la gode.",
    bulshit7: "Un prestito a buon mercato è al di là di ogni nuovo destino.", 
    bulshit8: "Il tuo denaro trasforma le azioni universali.", 
    bulshit9: "Il denaro alleggerisce i costi di chi lo prende in prestito.", 
    bulshit10: "Ricchezza e perseveranza forniscono il denaro per i poveri.",
    bulshit11: "I buoni investitori diffondono delle grandi azioni oltre le dimensioni.",
    bulshit12: "Libertà e spazio trasformano il significato astratto del denaro.",
    bulshit_corps: `Indica <b>il livello di significatività delle seguenti frasi</b> riguardanti la finanza utilizzando la scala sottostante a sei punti.`,
    end: "Grazie per la tua partecipazione."
}

export const en = {
    button: 'Continue',
    next: 'Next',
    button1: 'Start',
    button2: 'Accept and continue',
    button3: "Start the experiment",
    home_title: 'Welcome',
    home_corps1: `We would like to better understand the <b>financial decision-making processes</b>.
        To do so, in this study we will show you financial information concerning different investment funds. Afterwards, we will ask you to respond to a few questions. Your responses remain completely confidential. The study will take around <b>20 minutes</b>.`,
    home_corps2: `Your participation in the study is voluntary. By continuing, you confirm that you are at least 18 years old. You can choose to end your participation at any time.
     You can contact the researchers responsible for the study at the following email address: <i><u>milos.borozan@univ-rouen.fr</u></i>.`,
    home_corps3: `<i>The data will not be analysed individually, but only in aggregated form, with the data of all participants.</i>`,
    contact: `contact :  <u>milos.borozan@univ-rouen.fr</u>`,
    form_title: 'Necessary information',
    form_corps1: 'Please enter your details in the form below. All information will remain anonymous and confidential.', 
    form_age: 'Age',
    form_genre: ['Gender', 'Male', 'Female', 'Other'],
    form_prof: 'What is your profession?',
    form_main: ['Dominant hand', 'Right', 'Left'],
    form_souris: ['Hand on the mouse', 'Right', 'Left'],
    form_accept: `By continuing, I give my consent to the use of data concerning me in anonymous and aggregated form, for the purposes of scientific research. <br />I voluntarily agree to participate in the study and I understand that I can withdraw from the study at any time, without giving any explanation.`,
    calib_corps1: `During this experiment, we will use eye-tracking and mouse-tracking technologies.
    Before we begin, to make you familiarize with how the study is conducted, we will do <b> a few test trials</b>.
    This phase will also allow the for the calibration of the instruments.`,
    calib_corps2: `On the next page, a <b>cross</b> will appear. <b>Please keep your eyes on it at all times</b>.`,
    calib_label: ['Left', 'Right'],
    calib_consigne1: ['After you click on the start button  "+", please click as fast as possible on the button on "top', 'of your screen"'],
    calib_consigne2: `The options will be displayed once you cross the red line (<i><b>Attention</b> ! the line will not be visible later during the task</i>).`,
    risk_question: `<b>How do you see yourself - are you generally a person who is fully prepared to take risks or do you try to avoid taking risks?</b> <i>(Before you answer, please take a moment to reflect on your experience and the decisions you have made in different areas (education, relationships, health, shopping, investing, etc.) and different times in your life.)</i>`,
    risk_lab: ['Unwilling to take risks', 'Fully prepared to take risks'],
    risk_corps1: `You will participate in <b>a quick little game</b> before continuing the experiment.
    Please go to the <b>window on the right/left and follow the in-game instructions</b>.`,
    risk_corps2: ` When you're done, return to this window and <b>manually enter your performance</b> in the fields below.`, 
    risk_form: ['Try', 'Please insert only numbers'],
    consigne_un_corps1: `The aim of this section is to describe the overall structure of the experiment. Please read all instructions <b>carefully</b>.`, 
    consigne_un_corps2: `Investment decisions are usually based on data on different companies or investment funds that a user takes into consideration. This type of data is presented in a standardized way in the financial documents (<i>image 1</i>).`,
    consigne_un_corps3: `Each financial document has the same structure and has 4 sections: 
    "<b>Charges</b> ", "<b>Objectives and investment policy</b>", "<b>Risk and reward profile</b>" and "<b>Past performance</b> ".`,
    consigne_deux_corps1: `Therefore, we will ask you to <b>carefully review certain financial documents</b>.
    Then we'll ask you a few <b>questions</b> about it and you'll be presented with the choice interface. (<i>image 2</i>). You should answer as <b>quickly</b> and <b>accurately</b> as possible.`,
    consigne_deux_corps2: ` The time available to consult each financial document will be <b>limited</b>.
    Please consider each document separately.
    We remind you that there are <b>no right or wrong</b> answers, since we are only interested in your own preferences.`,
    consigne_deux_corps3: `Before starting, to let you familiarize with the documents, an example of a financial document will be presented to you, with no time limit. Simply click on continue to begin the experiment.`,
    consigne_image1: `<i><u>Image 1</u></i> : Investment fund information interface`,
    consigne_image2: `<i><u>Image 2</u></i> : Choice interface`,
    choice_lab: ['No', 'Yes'],
    choice_q1: "Based on the information that you just saw, would you invest your money in this fund?",
    choice_q2: "You must respond as quickly and accurately as possible.",
    question_un_q: "Please rate your level of confidence in this decision on the scale below.",
    question_un_lab: ['Completely unsure', 'Completely sure'],
    question_deux_q: `Do you remember the <b>level of risk</b> indicated for the investment fund you have just considered? Please indicate using the scale below.`,
    question_trois_q: "Was the information presented sufficient for you to make your investment decision?",
    question_trois_lab: ["Not at all sufficient / You would need additional information to make the decision", 'Completely sufficient'],
    question_quatre_q: `What type of information was the most important to your decision? Please indicate their relative importance using the scale below.?`,
    question_quatre_lab: ['Not so important', 'Very important'],
    question_quatre_options: ['Charges', 'Objectives and investment policy', "Risk and reward profile", 'Past performance'],
    scale_un: "How much have you relied on your own experiences and preferences to make the decision?",
    scale_un_value: ["Not at all", "A lot"],
    scale_deux: "How relevant is such a decision for you personally?",
    scale_deux_value: ["Not at all relevant", "Very relevant"],
    scale_trois: "How much effort have you put in to make a good decision?",
    scale_trois_value: ["No effort at all", "A lot of effort"],
    scale_quatre: "How much experience do you have with this kind of decision?",
    scale_quatre_value: ["No experience at all", "A lot of experience"],
    scale_cinq: "Suppose you had $100 in a savings account and the interest rate was 2% per year. After 5 years, how much do you think you would have in the account if you left the money to grow?",
    scale_cinq_value: ["More than 110 €", "Exactly 110 €", "Less than 110 €", "Don't know", "Prefer not to say"],
    scale_six: "Imagine that the interest rate on your savings account was 1% per year and inflation was 2% per year. After 1 year, how much would you be able to buy with the money in this account?",
    scale_six_value: ["More than today", "Exactly the same", "Less than today", "Don't know", "Prefer not to say"],
    scale_sept: "If interest rates rise, what will typically happen to bond prices?",
    scale_sept_value: ["They will rise", "They will fall", "They will stay the same", "There is no relationship between bond prices and the interest rate", "Don't know", "Prefer not to say"],
    scale_huit: "A 15-year mortgage typically requires higher monthly payments than a 30-year mortgage, but the total interest paid over the life of the loan will be less.",
    scale_neuf: "Buying a single company’s stock usually provides a safer return than a stock mutual fund.",
    scale_neuf_huit_value: ["True", "False", "Don't know", "Prefer not to say"],
    scale_dix: "A bat and a ball cost 1,10€ in total. The bat costs 1€ more than the ball. How much does the ball cost?",
    scale_dix_value: ["1 cent", "5 cents", "10 cents"],
    scale_onze: "If it takes 5 machines 5 minutes to make 5 widgets, how long would it take 100 machines to make 100 widgets?",
    scale_onze_value: ["1 minute", "5 minutes", "10 minutes"],
    scale_douze: "In a lake, there is a patch of lily pads. Every day, the patch doubles in size. If it takes 48 days for the patch to cover the entire lake, how long would it take for the patch to cover half of the lake?",
    scale_douze_value: ["12 days", "24 days", "47 days"],
    scale_corps: "It's almost over! You have to answer a few questions.",
    scale_corps1: "Just one more step.",
    bulshit_label: ["Not at all meaningful/worth considering", "Hardly meaningful/worth considering", "Slightly meaningful/worth considering", "Rather meaningful/worth considering", "Meaningful/worth considering", "Very meaningful/worth considering"],
    bulshit1: "A fool and his money are soon parted.", 
    bulshit2: "A budget tells us what we can’t afford, but it doesn’t keep us from buying it.",
    bulshit3: "Finance is not merely about making money. It’s about achieving our deep goals and protecting the fruits of our labor.",
    bulshit4: "Every time you borrow money, you are robbing your future self.",
    bulshit5: "Inflation is taxation without legislation.",
    bulshit6: "Wealth is not his that has it, but his that enjoys it.",
    bulshit7: "A cheap loan is beyond all new destiny.", 
    bulshit8: "Your money transforms universal actions.", 
    bulshit9: "Money eases the costs of those who borrow.", 
    bulshit10: "Wealth and perseverance provide money for the poor.",
    bulshit11: "Good investors spread large shares beyond size.",
    bulshit12: "Freedom and space transform the abstract meaning of money.",
    bulshit_corps: `Please rate <b>the level of meaningfulness of the following sentences</b> regarding finances using a given six-point scale.`,
    end: "Thank you for your participation."
}